config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe 
  get 'general_shopping_list', to: 'users#shopping_list'
  resources :users do
    resources :recipes do
      resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    end
  end
  root "recipes#public"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'recipe_id', dependent: :destroy, class_name: 'RecipeFood'
  has_many :foods, foreign_key: 'recipe_id', dependent: :destroy, class_name: 'RecipeFood'

  attribute :public, :boolean, default: false
  validates :name, :preparation_time, :cooking_time, :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show update]

  def index
    @recipes = Recipe.includes([:user]).where(user_id: current_user.id).order(created_at: :desc)
  end

  def new
    @user = current_user
    @recipe = Recipe.new
  end

  def update
    return unless @recipe.update(recipe_params)

    respond_to do |format|
      format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
      format.js # Handles AJAX response
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to user_recipes_path(current_user.id), notice: 'Recipe Added successfully!'
    else
      render :show
    end
  end

  def show
    @recipe = Recipe.includes([:user]).find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes([:food])
  end

  def public
    @public_recipes = Recipe.includes(:foods, :user).where(public: true).order('created_at DESC')
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    text = @recipe.public? ? 'public' : 'private'

    if @recipe.save
      flash[:notice] = "#{@recipe.name} is now #{text}!"
    elsif @recipe.errors.any?
      flash[:alert] = @recipe.errors.full_messages.first
    end
    redirect_to user_recipe_path(id: @recipe.id, user_id: current_user.id)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to user_recipes_path(current_user.id), notice: 'Recipe deleted!'
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/_card.html.erb
<div class="card mb-3" style="width: 50rem;">
  <div class="card-body d-flex space-between">
    <div class="card-body d-flex flex-column">
      <h5 class="card-title">
        <%= link_to recipe.name, user_recipe_path(id: recipe.id, user_id: recipe.user.id) %>
      </h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= recipe.user.name %></h6>
      <p class="mt-4"><%= recipe.description %></p>
    </div>
    <div class="card-body d-flex flex-column text-center">
    <p class="card-text">Total food items: <%= recipe.foods_counter %></p>
    <p class="card-text">Total Price: $
    <% sum = 0 %>
    <% recipe.foods_total_price %>
    </p>
    </div>
  </div>
  <% if can? :manage, recipe %>
    <%= button_to "Delete", user_recipe_path(recipe.user, recipe.id), method: :delete, class: "btn btn-danger m-3 ms-4" %>
  <% end %>
</div>

app/views/recipes/_public_card.html.erb
<div class="card mb-3" style="width: 50rem;">
  <div class="card-body d-flex space-between">
    <div class="card-body d-flex flex-column col-md-8">
      <h5 class="card-title">
        <%= link_to recipe.name, user_recipe_path(id: recipe.id, user_id: recipe.user.id) %>
      </h5>
      <% if recipe.user.present? %>
        <h6 class="card-subtitle mb-2 text-muted"><%= recipe.user.name %></h6>
      <% else %>
        <h6 class="card-subtitle mb-2 text-muted">Unknown User</h6>
      <% end %>
      <p class="mt-4"><%= recipe.description %></p>
    </div>
    <div class="card-body d-flex flex-column text-center col-md-4">
    <p class="card-text">Total food items: <%= recipe.foods_counter %></p>
    <p class="card-text">Total Price: $
      <%=  recipe.foods_total_price  %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<section class="d-flex flex-column align-items-center">
  <h1 class="text-center mb-5">Recipes</h1>

  <div class="d-flex flex-column">
    <%= link_to "Add New Recipe", new_user_recipe_path, class: "btn btn-primary mb-2" %>


    <% if @recipes.empty? %>
      <h2 class="text-center">The list is empty.</h2>
    <% else %>
      <% @recipes.each do |recipe| %>
      <%= render partial: 'recipes/card', locals: { recipe: recipe }  %>
      <% end %>
    <% end %>
  </div>
</section>

app/views/recipes/new.html.erb
<section class="d-flex flex-column align-items-center justify-content-center w-50 mx-auto">
  <h1 class="text-center mb-5">Add a Recipe</h1>

    <%= form_with model: @recipe, url: user_recipes_path(@user, @recipe), method: :post, :html => {:class => "w-50 mt-4"} do |form| %>
      <div class="form-group mt-3">
        <%= form.text_field :name, class: "form-control", placeholder: "Recipe" %>
      </div>
      <div class="form-group mt-3">
        <%= form.text_field :preparation_time, class: "form-control", placeholder: "Preparation Time" %>
      </div>
      <div class="form-group mt-3">
        <%= form.text_field :cooking_time, class: "form-control", placeholder: "Cooking Time" %>
      </div>
      <div class="form-group mt-3">
        <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
      </div>
      <div class="field form-control mt-3">
        <%= form.check_box(:public, { class: "form-check-input" }, true, false) %>
        <%= form.label "Public", class: "form-check-label" %>
    </div>
      <button type="submit" class="btn btn-primary mt-3">Submit</button>
    <% end %>
  
</section>

app/views/recipes/public.html.erb
<h1 class="text-center mb-5">Public Recipes</h1>
<section class="d-flex flex-column align-items-center">
  <% @public_recipes.each do |recipe| %>
  <%= render partial: 'recipes/public_card', locals: { recipe: recipe }  %>
  <% end %>

  <% if @public_recipes.empty? %>
    <h2 class="text-center">This list is empty</h2>
  <% end %>
</section>

app/views/recipes/show.html.erb
<section class="container">
  <h1 class="text-center mb-5"><%= @recipe.name %></h1>
  <span class="badge badge-primary">Private</span>
  <div class="recipe-info d-flex justify-content-around col-md-12">
    <div>
      <h5>Preparation time: <%= @recipe.preparation_time %></h5>
      <h5>Cooking time: <%= @recipe.cooking_time %></h5>
      <div>
        <h3 class="mt-5">Description</h3>
        <p><%= @recipe.description %></p>
      </div>
    </div>
    <div class="recipe-stat col-md-3">
       <h3><% if @recipe.public? %>Public<%else%>Private<%end%></h2>
      <% if can? :update, @recipe %>
        <label class="switch">
          <input type="checkbox" <%= @recipe.public? ? 'checked' : '' %> disabled>
          <span class="slider round"></span>
        </label>
      <% end %>
      <% if can? :update, @recipe %>
        <%= button_to @recipe.public? ? 'Make Private' : 'Make Public', toggle_recipe_path( @recipe.id), method: :post, remote: true ,
              class: 'btn btn'%> 
      <%else%>
     
      <p> Be Authorize </p>
      <%end%>
    </div>
  </div>
  <div class="mt-5 d-flex justify-content-around">
    <%= link_to "Generate shopping list", general_shopping_list_path, class: 'btn btn-primary' %>

    <% if can? :update, @recipe %>
      <%= link_to "Add ingredient", new_user_recipe_recipe_food_path(@recipe.user, @recipe), class: "btn btn-danger" %>
    <% end %>
  </div>

  <table class="table table-striped table-bordered mt-5 text-center">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @recipe.recipe_foods.each do |ingredient| %>
    <tr>
      <th scope="row"><%= ingredient.food.name %></th>
      <td><%= ingredient.quantity %></td>
      <td>$ <%= ingredient.quantity* ingredient.food.price %></td>
      <td>
        <div class="d-flex justify-content-center gap-3">
          <%= button_to "Delete", user_recipe_recipe_food_path(@recipe.user, @recipe.id, ingredient.id), method: :delete, class: "btn btn-danger" %>
          <%= link_to "Edit", edit_user_recipe_recipe_food_path(@recipe.user, @recipe, ingredient), class: "btn btn-primary" %>
        </div>
      </td>
    </tr>
    <% end %>
    <tr>
  </tbody>
</table>
</section>

app/views/recipes/update.js.erb
const toggleButton = document.querySelector(".toggle-button");
toggleButton.checked = <%= @recipe.public %>;