config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe 
  get 'general_shopping_list', to: 'users#shopping_list'
  resources :users do
    resources :recipes do
      resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    end
  end
  root "recipes#public"
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates_uniqueness_of :name, scope: :user_id, message: ' of food is already in your list'
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit destroy]
  before_action :authenticate_user!

  # GET /foods
  def index
    @foods = current_user.foods
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods
  def create
    @food = current_user.foods.new(food_params)
    @food.name = @food.name.titleize

    if @food.save
      redirect_to foods_url, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /foods/1
  def destroy
    @food.destroy

    redirect_to foods_url, notice: 'Food was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/views/foods/_food.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td><%= number_to_currency(food.price) %></td>
  <td><%= button_to "Delete", food, method: :delete, class: 'delete-link' %></td>
</tr>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='mb-3'>
    <%= form.label :name, style: "display: block", class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class='mb-3'>
    <%= form.label :measurement_unit, style: "display: block", class: 'form-label' %>
    <%= form.text_field :measurement_unit, class: 'form-control' %>
  </div>

  <div class='mb-3'>
    <%= form.label :price, style: "display: block", class: 'form-label' %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class='mb-3'>
    <%= form.label :quantity, style: "display: block", class: 'form-label' %>
    <%= form.number_field :quantity, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/foods/index.html.erb
<%= stylesheet_link_tag 'foodindex' %>
<p style="color: green"><%= notice %></p>

<div class='foodindex-container'>
  <%= link_to "Add food", new_food_path, class: 'add-btn' %>
  <% if @foods.empty? %>
    <p class="text-center"> <i> Your food list is empty </i></p>
  <% else %>
    <table>
      <thead>
        <tr>
          <th>Food</th>
          <th>Measurement unit</th>
          <th>Unit price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <%= render food %>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/foods/new.html.erb
<div class='form-container'>
  <h1>New food</h1>

  <%= render "form", food: @food %>

  <br>

  <div>
    <%= link_to "Back to foods", foods_path %>
  </div>
</div>