config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe 
  get 'general_shopping_list', to: 'users#shopping_list'
  resources :users do
    resources :recipes do
      resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    end
  end
  root "recipes#public"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'

  validates :quantity, presence: true

  after_save :update_foods_counter, :update_foods_total_price
  before_destroy :decrement_foods_counter, :reduce_foods_total_price

  private

  def update_foods_counter
    recipe.increment!(:foods_counter)
  end

  def update_foods_total_price
    recipe.increment!(:foods_total_price, (food.price * quantity))
  end

  def reduce_foods_total_price
    recipe.decrement!(:foods_total_price, (food.price * quantity))
  end

  def decrement_foods_counter
    recipe.decrement!(:foods_counter)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = current_user.foods
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(quantity: params[:quantity], food_id: params[:food_id])
    if @recipe_food.save
      redirect_to user_recipe_url(@recipe.user, @recipe), notice: 'Ingredient has been added successfully!'
    else
      render :new, alert: 'Something went wrong!'
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @foods = Food.all
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_update_params)
      redirect_to user_recipe_url(@recipe_food.recipe.user, @recipe_food.recipe),
                  notice: 'Recipe food updated Successfully!'
    else
      redirect_to user_recipe_url(@recipe_food.recipe.user, @recipe_food.recipe), alert: 'Something went wrong!'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.find(params[:id])
    @recipe_food.destroy
    flash[:notice] = 'Ingredient deleted!'
    redirect_to user_recipe_url(@recipe.user, @recipe)
  end

  private

  def recipe_update_params
    params.permit(:quantity, :food_id)
  end
end

app/views/recipe_foods/edit.html.erb
<section class="d-flex flex-column align-items-center w-50 mx-auto">
  <h1 class="text-center">Edit ingredient</h1>
    <%= form_with url: user_recipe_recipe_food_path, method: :patch, :html => {:class => "w-50 mt-4"} do |form| %>
      <div class="form-group mt-3">
        <%= form.select :food_id, @foods.collect  {|food| [food.name, food.id]},{ include_blank: false}, class: "form-control", placeholder: "Recipe" %>
      </div>
      <div class="form-group mt-3">
        <%= form.number_field :quantity, class: "form-control", placeholder: "Quantity" %>
      </div>
      <button type="submit" class="btn btn-primary mt-3">Edit</button>
    <% end %>

</section>

app/views/recipe_foods/new.html.erb
<section class="d-flex flex-column align-items-center w-50 mx-auto">
  <h1 class="text-center">Add ingredient</h1>
    <%= form_with url: user_recipe_recipe_foods_path(params[:recipe_id]), method: :post, :html => {:class => "w-50 mt-4"} do |form| %>
      <div class="form-group mt-3">
        <%= form.select :food_id, @foods.collect  {|food| [food.name, food.id]},{ include_blank: false}, class: "form-select" %>
      </div>
      <div class="form-group mt-3">
        <%= form.number_field :quantity, class: "form-control", placeholder: "Quantity" %>
      </div>
      <button type="submit" class="btn btn-primary mt-3">Add</button>
    <% end %>
</section>

app/views/recipe_foods/shopping.html.erb
<p style="color: green"><%= notice %></p>

<div class='shopping-container'>
  <% if @lists.empty? %>
    <h2 class="text-center">Your shopping list is empty.</h2>
  <% else %>
    <table>
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @lists.each do |item| %>
          <tr>
            <td><%= item.food.name %></td>
            <td><%= item.quantity %> <%= item.food.measurement_unit %></td>
            <td>$ <%= food.price %></td>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>